### ISSUE TITLE
数据库预设数据没有

### ISSUE THREAD

**Issue by luxiao9999** [AeroWang/XanaduCompany#12]
数据库预设数据，比如默认一个admin，默认role和permission数据。
否则admin没法体验啊，用户注册不了

**Comment by AeroWang** [comment]
你是真不舍得点进去看啊
<img width="600" alt="image" src="https://github.com/AeroWang/XanaduCompany/assets/44799877/c4921510-40ad-496d-bbe7-135e97b8c7fa">
