### ISSUE TITLE
web dir ,  yarn dev can't run success

### ISSUE THREAD

**Issue by liziqiang0523** [AeroWang/XanaduCompany#15]
ziqiangli@ZiQiangdeMacBook-Pro web$ yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@vue/eslint-config-standard > eslint-import-resolver-webpack@0.12.2" has unmet peer dependency "webpack@>=1.11.0".
warning " > compression-webpack-plugin@5.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > style-resources-loader@1.5.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0 || ^5.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 117.67s.
ziqiangli@ZiQiangdeMacBook-Pro web$ yarn dev
yarn run v1.22.19
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AeroWang** [comment]
并不是每个项目都是 `yarn dev` 或者 `npm run dev` 的，具体要看项目内的 `package.json` -> `scripts` 中的命令
